Comment section
NicolasAndrehh/JavaScript-Group-Capstone pull request #28
Opened 2023-03-15 14:08 UTC by johnie261

I did the following:

- Created a comment section and styled it.
- Created a form to input a name and the comment and also a submit button.

2023-03-15 16:37 UTC, NicolasAndrehh requested changes
## Status: Changes Required ♻️
Congratulations @johnie261, you did a great job but there are some things that can be improved!

## Highlights
- Very clean code
- Good GitFlow
- Good job with the media queries

## Required Changes 
There are a few changes that I request before approving the PR:

- Check the comments below

*Feel free to leave a comment tagging me if any changes is not clear at all*

2023-03-15 16:37 UTC, NicolasAndrehh commented on src/popup/modal.js
> +        </div>
I kindly recommend you to check the requirements again, you are showing the comments section, that great but the comments of that section should be from the data from the API of this endpoint /apps/:app_id/comments, you can add some comments using the following structure in the body of the POST request: 

{
    "item_id": "item1",
    "username": "Jane",
    "comment": "Hello"
}

You can use the involvement API class and add a method to get comments, remember that the post comment method is not a requirement for this activity you'll do it on an upcoming activity

You can take a look at the get likes method to create the get comments method they suppose to be alike

2023-03-15 16:53 UTC, johnie261 commented
@NicolasAndrehh thanks for the suggestion man

2023-03-15 21:21 UTC, johnie261 commented
Something happened while resolving conflict,,,let me sole it

2023-03-15 21:46 UTC, NicolasAndrehh requested changes
## Status: Changes Required ♻️
Congratulations @johnie261, you did a great job but there are some things that can be improved!

## Highlights
- Good job with the involvementAPI methods
- Great GitFlow

## Required Changes 
There are a few changes that I request before approving the PR:
- I like that you're experimenting with box-shadow, but I kindly recommend you follow the design of the page, try to put the comment button alike the homepage buttons, stick to the colors and padding, you can use the border shadow as a hover effect, and experiment with the width or position of the button
- Check the comments below for more changes

*Feel free to leave a comment tagging me if any changes are not clear at all*

2023-03-15 21:46 UTC, NicolasAndrehh commented on src/popup/comment.js
> +  }
At the end of the URL where it says 'item1' should be replaced with the item id, that id should be passed as a parameter in the addComments(itemId) method, and then when you use the fetch method it should be something like this `fetch('${this.url}${itemId}', { the rest of the code })` that way if you pass the id 6 as a parameter you'll get all the comments from the item 6, and for checking if it working you'll need to post some comments for the specifics ids that you'll check and remember to use postman to check if your POSTS were successful

2023-03-15 21:46 UTC, NicolasAndrehh commented on src/popup/comment.js
> +  }
Excellent implementation of the methods, but I recommend you put those methods on the InvolvementAPI that was already created on `modules/involvementAPI.js`.
After doing that may you would need to change some imports in your other files

2023-03-16 15:00 UTC, NicolasAndrehh approved these changes
## PR Accepted ✅
Congratulations @johnie261, you did a great job, there's nothing else to say more than let's merge it! 🎉

### Highlights
- Awesome job implementing the comments for each Character
- Very clean code

2023-03-16 15:09 UTC, merged